import { notFound } from 'next/navigation';
import { money } from '@proven/engine';
import { getReportData } from '../report-data';
import { PrintButton } from './print-button';
import './report.css';

export const metadata = {
  title: 'Portfolio Report · Proven',
};

/**
 * The portfolio report, laid out for paper.
 *
 * A print-styled page rather than a generated PDF file: the browser's own
 * "Save as PDF" produces a better document than hand-drawn PDF syntax, keeps
 * the text selectable, and means the report can be read on screen before
 * anyone decides they want a copy of it.
 */
export default async function PortfolioReportPage({
  params,
}: {
  params: Promise<{ orgId: string }>;
}) {
  const { orgId } = await params;
  const data = await getReportData(orgId);
  if (!data) notFound();

  return (
    <div className="report-page">
      <PrintButton />

      <article className="report">
        <header className="rep-head">
          <div className="rep-brand">
            {/* eslint-disable-next-line @next/next/no-img-element -- fixed-size
                brand mark; next/image adds a loader for no benefit in print. */}
            <img src="/assets/logo_only__1_-removebg-preview.png" alt="" />
            <div>
              <h1>Portfolio Report</h1>
              <p>Proven, Turning Potential into Proof</p>
            </div>
          </div>
          <div className="rep-meta">
            {/* The funder's own mark, for a report going to their board. */}
            {data.orgLogoUrl && (
              /* eslint-disable-next-line @next/next/no-img-element -- signed URL */
              <img className="rep-orglogo" src={data.orgLogoUrl} alt="" />
            )}
            <div>{data.generatedOn}</div>
            <div>{data.orgName}</div>
            <div>
              {data.total} funded {data.total === 1 ? 'business' : 'businesses'}
            </div>
          </div>
        </header>

        <div className="rep-tiles">
          <div className="rep-tile">
            <div className="l">Total funding</div>
            <div className="v">{money(data.totalFunding)}</div>
          </div>
          <div className="rep-tile">
            <div className="l">Jobs supported</div>
            <div className="v">{data.jobs}</div>
          </div>
          <div className="rep-tile">
            <div className="l">Portfolio health</div>
            <div className="v">{data.avgScore}/100</div>
          </div>
          <div className="rep-tile">
            <div className="l">Needs attention</div>
            <div className="v">{data.needAttention}</div>
          </div>
        </div>

        <h2 className="rep-section">Funded businesses, by health score</h2>

        <table className="rep-table">
          <thead>
            <tr>
              <th>Business</th>
              <th>Owner</th>
              <th className="r">Grant</th>
              <th className="r">Rel.</th>
              <th className="r">Score</th>
              <th className="c">Band</th>
              <th>Credit readiness</th>
              <th>Reporting</th>
              <th className="r">Evid.</th>
              <th className="r">Jobs</th>
            </tr>
          </thead>
          <tbody>
            {data.rows.map((r) => (
              <tr key={r.name}>
                <td>
                  <strong>{r.name}</strong>
                  <div className="sub">
                    {[r.industry, r.region].filter(Boolean).join(' · ')}
                  </div>
                </td>
                <td>{r.owner || '—'}</td>
                <td className="r">{r.grant === null ? '—' : money(r.grant)}</td>
                <td className="r">{r.released}%</td>
                <td className="r">
                  <strong>{r.score}</strong>
                </td>
                <td className="c">
                  <span className={`rep-band ${r.tier}`}>{r.band}</span>
                </td>
                <td>{r.readiness}</td>
                <td className={r.reportingLate ? 'late' : ''}>{r.reporting}</td>
                <td className="r">{r.coverage}%</td>
                <td className="r">{r.jobs}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <p className="rep-note">
          Scores are calculated from four weighted measures: sales trend 35%,
          spending control 25%, reporting consistency 20%, customer growth 20%.
          Credit readiness is evidence to support, not replace, a formal credit
          assessment.
        </p>

        {/* Says where the document came from, on the page itself. The browser
            prints its own header with the source URL, which a reader could
            mistake for the origin of the figures; this states it plainly. */}
        <footer className="rep-foot">
          Generated by Proven on {data.generatedOn} for {data.orgName}. Figures are
          reported by each business and are not editable in this document.
        </footer>
      </article>
    </div>
  );
}
